export const SEND = "send";
export const SUCCESS = "success";
export const ERROR = "error";
export const ADD_TAG = "add tag";
export const NAME = "name";
export const TAG = "tag";
export const INPUT_VALUE_CHANGE = "input value change";
export const INPUT_BLUR_CHANGE = "input blur change";
export const RESET_INPUT = "reset input";
